
export const AUTHENTICATE_USER_START = 'AUTHENTICATE_USER_START';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAIL = 'AUTHENTICATE_USER_FAIL';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

export const CLEAR_ERROR_MESSAGE = "LEAR_ERROR_MESSAGE";

export const LOGOUT = "LOGOUT";
